### ISSUE TITLE
Missing mautic:import command for importing contact in background

### ISSUE THREAD

**Issue by taicv** [mautic/mautic-documentation#34]
> Warning background import requires to run php /path/to/mautic/app/console mautic:import command periodically. Add it to your cron tab.

https://docs.mautic.org/en/contacts/import-contacts

**Comment by RCheesley** [comment]
Hi @taicv thanks for raising this - do you mean that you think the cron job should be mentioned here specifically?  It wasn't completely clear to me what the problem was, or what you were suggesting to fix it.

It seems like maybe you might mean that this command is missing from https://docs.mautic.org/en/setup/cron-jobs and/or it should be included on the import contacts page?

Perhaps you would like to make some edits to the pages to include the information you feel to be missing?  Either via a PR or by editing the pages using the links at the bottom of the page and submitting a separate PR for each page.

Let me know if you need any help, I'm happy to help you with making these contributions!

**Comment by taicv** [comment]
Thanks @RCheesley for prompt reply and sorry for the not describing clearly.

Actually, the page I wanna improve is Cron Jobs page
https://github.com/mautic/mautic-documentation/blob/master/pages/02.Setup/02.Cron%20Jobs/docs.en.md
But when I creating issue, it didn't include the page in my message.
---
So for more detail, my issue is:  "The Document about Cron Jobs (02.Setup/02.Cron%20Jobs/docs.en.md) didn't mention about contact import command, It should because I think importing is also an important task.

I really wanna contribute but my English is not so good. Let me try to create a PR as you suggested.

Thank you

**Comment by RCheesley** [comment]
OK, the easiest way is to click the link at the bottom of the documentation, and then click 'edit'.  Make your changes, then click on the button to 'propose changes' and then make a pull request.

We will then review the proposed changes (once you make the pull request) and if there are any changes needed can either give advice, or we can add a commit to implement the change.

Looking forward to seeing your suggestions :)

**Comment by swati-thacker13** [comment]
This issue will be clused by PR - https://github.com/mautic/mautic-documentation/pull/81

**Comment by RCheesley** [comment]
Resolved by #81
