### ISSUE TITLE
Documentation translation - how and where to pull

### ISSUE THREAD

**Issue by aiac** [mautic/mautic-documentation#43]
Hi! We got polish translation of Mautic documentation, and we would like to contribute this way. How and where can we push this? Contributing notes are not covering this. It would be nice if someone can change language @ https://docs.mautic.org

**Comment by RCheesley** [comment]
Hi there, great to hear that there is interest 
In translating the documentation into Polish!

We are using Grav as our platform, and it supports multilingual natively. 

We would require all the pages to be translated fully before we go about adding a new translation. We would also need a team of people committed to translating, reviewing, and editing
 on an ongoing basis.

What I would suggest as a starting point is joining the [Education Team Slack channel](https://mautic.slack.com/archives/CQGQ0D4KU) (Get an invite at [mautic.org/slack](https://mautic.org/slack)), and asking everybody who would be willing to contribute to the documentation in Polish to join as well. Then we can spin up a small working group to focus on this. 

If you already have the documentation translated, it would be super helpful if you could share this, for example in a Google doc or several Google Docs, so that we can review.  Please make sure that any translation is current, as since we re-platformed the structure has been changed.

Excited to work on this with you, look forward to chatting more in Slack!

**Comment by oltmanns-leuchtfeuer** [comment]
Was postponed to be worked at in the Slack channel, thus I close this until we get a new spin and need to re-open. :)
